# Generated by Django 5.0.3 on 2024-04-07 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tareasApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="personas",
            new_name="tareas",
        ),
    ]
